### ISSUE TITLE
wp-bootstrap-navwalker conflicts with bootstrap shortcodes

### ISSUE THREAD

**Issue by Travo100** [wp-bootstrap/wp-bootstrap-navwalker#121]
Used wp-bootstrap-navwalker with bootstrap shortcodes(http://wordpress.org/plugins/bootstrap-shortcodes/) on a theme I am developing. Looks like the shortcodes plugins conflicts with wp-bootstrap-navwalker and it does not let wp-bootstrap-navwalker give you access to a drop down menu. Most likely somewhere in the javascript.

**Comment by Bradley-D** [comment]
The plugin would be loading its own JS files that will clash with the JS already rolled in your theme. Check to see if the plugin has an option to use the JS from the theme already, or try this plugin (https://wordpress.org/plugins/easy-bootstrap-shortcodes/), it has a settings page that allows you to use the themes JS.

**Comment by pattonwebz** [comment]
@Travo100 I think @Bradley-D is probably right about there being a JS conflict because of the plugin including the script and so would your theme.

Were you able to try his suggestion of using the [easy bootstrap shortcodes](https://wordpress.org/plugins/easy-bootstrap-shortcodes/) plugin and setting it not to include the JS a second time?

**Comment by SideQuestDIY** [comment]
When using the _Bootstrap Shortcodes_ plugin it adds its own version of the bootstrap JS & CSS files. This causes conflicts if you have loaded the bootstrap JS & CSS files in your theme. The javascript conflicts will cause the menu to not dropdown.
