### ISSUE TITLE
Code Standards

### ISSUE THREAD

**Issue by bhubbard** [wp-bootstrap/wp-bootstrap-navwalker#133]
Hey guys I setup my project in Scrutinizer - https://scrutinizer-ci.com. 

My project had the latest version of wp-bootstrap-navwalker installed and it reported some things to look at. Thought I would post it here to get reviewed. 

![Scrutinizer Screenshot](https://cloud.githubusercontent.com/assets/3837/4172552/70d7c564-354a-11e4-8e21-f6339339dfba.png)

**Comment by SideQuestDIY** [comment]
Hey sorry for the late reply. 

Thanks for providing this. Errors presented here are not actually an issue. They appear that way to the tool because it is analyzing the single file. Since this walker is class extends WordPress's core walker class in this file those variables are not defines, but in the larger scope of the application they are.
