### ISSUE TITLE
dropdown not working

### ISSUE THREAD

**Issue by Tlamelo** [wp-bootstrap/wp-bootstrap-navwalker#149]
The menu has been working properly now it just stopped functioning properly.When i refresh the page it works for a sec then stops. I don't what the problem is?? and why the drop down menus aren't working the website is http://iwg-gti.org/

**Comment by rv8820** [comment]
I have the same issue.  Last week the dropdown was working fine, now it just disappears and I don't know why.

**Comment by rv8820** [comment]
OK, the navwalker have a conflict with Menu Image plugin (https://wordpress.org/plugins/menu-image/).  I disabled the plugin and it's working fine again.

**Comment by pattonwebz** [comment]
Hey Tlameo, rv8820

@rv8820 Glad you sorted your problem :) Did you figure out what the specific conflict was?

@Tlamelo Do you have the 'Menu Image' plugin installed on your site like rv8820 did? Also I looked at the site and I think I know why dropdowns aren't working. There's an error in your site's js and it's causing other aspects of your js to fail (like the Bootstrap JS for making dropdowns work).

The error reported in the console is found on line 14 of the `/iwgtheme/js/custom.js` file. I took a very quick look and I think I know what the problem is: your trying to use jQuery with the identifier of `$` however WordPress includes it's copy of the jQuery library in `.noConflict()` mode so you can't target it with `$` (other libraries use $ as shorthand too so laving it on by default would cause conflicts with many other js libraries).

The fix for the problem on line 14 of the file would be to add the following code before it:

`var $ = jQuery.noConflict();`

That sets the `$` variable to point to jQuery in that file. The rest of the function should work as expected after you assign jQuery to the `$` variable.

**Comment by rv8820** [comment]
@pattonwebz I didn't bother to look at it as I don't need the Menu Image plugin anymore, so I just disabled it straight-away.  I'll check it out later and see how.

**Comment by pattonwebz** [comment]
@rv8820 Don't worry about it, I was really just curious to find out if the problem is based in php or js. Don't go enabling the plugin again and breaking your menu on a live site, I'll just grab the plugin and install it on a dev site to see what happens :)

**Comment by rv8820** [comment]
@pattonwebz Great! Thanks.  I am interested to know also as I may use the Menu Image plugin next time.

**Comment by jarimos** [comment]
For me her was the trouble :)
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
