### ISSUE TITLE
Menu items do not appear on smaller resolutions

### ISSUE THREAD

**Issue by novosadskigari** [wp-bootstrap/wp-bootstrap-navwalker#152]
Hi,

I recently started developing my own wp themes and got an advice to use this method when implementing bootstrap3 menus in my themes.

This is probably a mistake on my end but I wanted to check with you also.

Menu works great and shows the submenus correctly but when I try opening the website on smaller devices and when the toggle menu button appears I'm not getting any menu items (when clicked none of the pages are visible)

This is how my code on the header.php looks like:

```
<nav class="navbar navbar-inverse bs-docs-nav col-md-9" role="banner">
                        <div class="navbar-header">
                          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                        </div>
                        <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation">
                          <ul class="nav navbar-nav">
                            <?php
                                wp_nav_menu( array(
                                    'menu'              => 'primary',
                                    'theme_location'    => 'primary',
                                    'depth'             => 2,
                                    'container'         => 'div',
                                    'container_class'   => 'collapse navbar-collapse',
                                    'container_id'      => 'bs-example-navbar-collapse-1',
                                    'menu_class'        => 'nav navbar-nav',
                                    'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
                                    'walker'            => new wp_bootstrap_navwalker())
                                );
                            ?>
                          </ul>
                        </nav>
```

Any advices?

Thanks a lot!

**Comment by pattonwebz** [comment]
Hey pevoje,

Seems the problem here is that the button to open the menu isn't targeting the correct class or Id of your menu container.

NOTE: I also think that you shouldn't have the `.collapsed` class on your button so it's removed in the code provided below.

The button targets the class `.bs-navbar-collapse` however your menu doesn't actually have that class as a wrapper. It should be targeting one of the classes (or preferably the ID) of the menu container that you specify in the `wp_nav_menu()` call.

If you change the button code to this it should work with the code you're using:

`<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">`

That should fix things to work for you like expected :)

**Comment by novosadskigari** [comment]
Hi pattonwebz,

thanks for your reply, but sadly this didn't solve my problem, I'm not managing to get my menu items displayed.

Sorry for bothering you but I just recently dev my wp themes and this may seem like a stupid question to you but it helps me alot :)

this is my current code after your suggestions:

```
<div class="navbar-header">
                          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
                        </div>
                        <nav class="navbar-collapse bs-navbar-collapse collapse" role="navigation">
                          <ul class="nav navbar-nav no-gutter">
                            <?php
                                wp_nav_menu( array(
                                    'menu'              => 'primary',
                                    'theme_location'    => 'primary',
                                    'depth'             => 2,
                                    'container'         => 'div',
                                    'container_class'   => 'collapse navbar-collapse',
                                    'container_id'      => 'bs-example-navbar-collapse-1',
                                    'menu_class'        => 'nav navbar-nav',
                                    'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
                                    'walker'            => new wp_bootstrap_navwalker())
                                );
                            ?>
                          </ul>
                        </nav>
```

**Comment by pattonwebz** [comment]
Hey again @pevoje,

We've all been beginners at some point before, you'll learn quicker the more questions you ask. The only stupid questions are the ones you already know the answer to  ;)

I really though this issue would be fixed by the button targeting the correct manu wrapper class/ID. No other problems stand out to me in this code.

Just so I'm certain I understand the problem this is what I think is happening, let me know if I'm wrong:
- The menu displays fine when it's the large size. 
- The menu button appears when the screen size is small. 
- Clicking the button doesn't open the menu as it should.

It'd really help if I could take a look at a live site that's showing the problem so I can check the html source and javascript all looks like it should. Do you have a version of the site online that I could take a look at?

If you do have one but you don't want to publicly post a link that's fine, you can email me the link (my email address is listed on my profile - just click my name to get there).

Reopening this issue as it's not solved like I thought it would be.

**Comment by novosadskigari** [comment]
You are right, you understood what is going on :)

Can't post the link public, sending you the link via email

**Comment by pattonwebz** [comment]
This issue has been fixed and wasn't directly related to the navwalker.
