### ISSUE TITLE
two active menu links in navigation

### ISSUE THREAD

**Issue by rakesh-baikar** [wp-bootstrap/wp-bootstrap-navwalker#170]
when i add same links in different menu links , two menu links active 

see screenshot

![Uploading screen.jpg…]()

**Comment by mindctrl** [comment]
@rakesh-baikar your screenshot is broken.

**Comment by pattonwebz** [comment]
If there are 2 links on the page that point to the same page and you visit that page I would expect that both links would be set as `.active`. This would be the expected behavior in any instance (not just with this navwalker) so I am confused as to what the issue here is.

I'm closing this issue now as its not been updated in several months but if @rakesh-baikar comes by and adds a screenshot or clarifies the issue I will re-open it.
