### ISSUE TITLE
multiple dropdowns opening simultaneously on click

### ISSUE THREAD

**Issue by yamaniac** [wp-bootstrap/wp-bootstrap-navwalker#197]
Hey Guys,

Thank you so much for this amazing plugin, Worked like a charm until recently.
The requirement was to add another drop-down. Although, that's done and it is working fine, The problem is that, whenever a menu with a drop-down is clicked another one with a drop down opens up and closes and on click as well
![sc](https://cloud.githubusercontent.com/assets/14869625/10131503/6e0b0bea-65ee-11e5-93d4-324f3d1d39a4.png)
. Any solutions would be greatly appreciated.

**Comment by mindctrl** [comment]
Make sure each one has a unique data-target attribute. If you can't figure it out, post your code here for both dropdowns.

**Comment by jamesgiroux** [comment]
I'm running into this issue too and it comes from not knowing where exactly to place my ul 'id'.  right now i've got it set statically within the $output of start_lvl but I'm not sure where it should go so that it works properly.  I think the best way is to append the $item->ID to the end of the data-activates attribute and also set it to the ul id for the sub menu/dropdown-content but I'm not sure how to add that into the class.  any ideas?

**Comment by yamaniac** [comment]
Hi James,

I had to deliver this project and was running out of time. So I got this sorted with a simple jquery animation "onClick". Has anyone else found a solution for this problem?

**Comment by mindctrl** [comment]
Can you share your markup? Without it we're just guessing.

**Comment by yamaniac** [comment]
$(document).ready(function(){
    $( ".dropdown-toggle" ).click(function() {
    $(".dropdown-menu").slideToggle('fast');
     });
 });

Just something quick and dirty. But does the job.

**Comment by mindctrl** [comment]
Sorry, I meant your HTML markup.

**Comment by bhubbard** [comment]
@yamaniac We recently updated to version 2.0.5, can you please update and let us know if you still are running into issues.
