### ISSUE TITLE
menu anchor text turns to RIGHT ARROW when no search results

### ISSUE THREAD

**Issue by KSVQ** [wp-bootstrap/wp-bootstrap-navwalker#242]
I came across this odd behavior. When I try to search for something, IF there are search results, the menu looks normal. IF there are NO search results, the anchor text on all menu items turns into a right arrow.

I don't even know how to begin understanding why this would happen??

**Comment by pattonwebz** [comment]
I tried to recreate this issue but on my install the arrows don't show when no search results are present. I would think that for the arrows to appear the most likely reason would be a class name change on the menu items.

Could you check the markup of the working (with results) menu and the non-working (no results) version and see if any class names change for me?

**Comment by KSVQ** [comment]
Yes. I checked and I have to say this is probably not a navwalker problem. I eliminated the menu all together and I still see the same issue with native wordpress menu. It's such a basic theme that I am quite puzzled at this point,,, Sorry about it.

**Comment by pattonwebz** [comment]
No need to apologize :) It's a fair assumption to make that a menu issue is likely tied to the navwalker.

Perhaps I could still make a few suggestions of what to look at to try find the cause. First I'd check the class names for differences like I suggested above. Also look to see if maybe a `<i>` tag or a `<span>` is getting added that the arrow might be attached to.

If there's no differences between the markup then it's likely a styling issue. Look at the elements in the menu to try find what adds the arrow. It could be a style attached to a `<li>` element and maybe even attached to a `:before` or `:after` pseudo-selector.

It's peculiar that this only affects search pages that have no results. Take a look at your search.php file. Check if there is maybe an `else` clause for times when no results are available. I've seen a lot of times that a hardcoded style block is added to the part of the template that deals with no results. 

Hope you find what the problem is soon!

**Comment by KSVQ** [comment]
I appreciate the suggestions :)

**Comment by KSVQ** [comment]
It was a plugin..
