### ISSUE TITLE
Text needs to be translation ready

### ISSUE THREAD

**Issue by carolinan** [wp-bootstrap/wp-bootstrap-navwalker#244]
As part of the WordPress.org theme review team, I see this code used frequently, and you would make the lives of theme authors and reviewers so much easier if this little text had a translation function:

`$fb_output .= '<li><a href="' . admin_url( 'nav-menus.php' ) . '">Add a menu</a></li>';`

**Comment by pattonwebz** [comment]
Duely noted, @Carolinan. It is actually already fixed in the next version of the walker for BS4 but I'll push a patch today with the string translated in the current version too :)

**Comment by pattonwebz** [comment]
@bhubbard, @twittem we should roll this back in

**Comment by bhubbard** [comment]
So the line referenced here was completely changed and no longer uses $fb_output as of 2.0.5. This new version has the empty reference for the text domain. 

https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/master/wp-bootstrap-navwalker.php#L213

```php
echo '<li><a href="' . esc_url( admin_url( 'nav-menus.php' ) ) . '" title="">' . esc_attr( 'Add a menu', '' ) . '</a></li>';
```

Not sure what we should use for the text-domain. We could use `wp-bootstrap-navwalker` and include our own translation file. 

However I think most devs/users just copy the project file into their projects and include it, which means they should be adding the text-domain that is used within their project/theme. We could also just use `text-domain` and have instructions for users to do a find/replace for it on the file.

**Comment by pattonwebz** [comment]
Yes most just copy into project and publish. As far as theme review guidelines go it's fine for people to use libraries like this one and for it to have it's own text domain. The OP of this issue is on theme review team and they allow this through so long as the string is translatable - I believe they are OK with it using it's own text domain but I can check to be sure before we decided what to use here.

If we were to use `text-domain` and instruct people to do a search-replace that could work too I think.

I'll close this issue again for now and we can discuss this further maybe on the projects page or wherever is appropriate.
