### ISSUE TITLE
Add Support for PHPUnit Testing

### ISSUE THREAD

**Issue by bhubbard** [wp-bootstrap/wp-bootstrap-navwalker#255]
Lets add testing!

**Comment by pattonwebz** [comment]
There are some tests in the repo now. I haven't used them manually but I see they run through travis.

I have to admit that I have rarely ever written unit tests any more complex than simply asserting classes exist the same as the kinds of tests we have in the repo. I'm lead to believe that we should ideally be doing more thorough testing and even passing in some test data for processing to assert the outcome is what we expect for ordinary, edge cases and exceptions. 

I do not have any experience with doing that kind of thorough testing with phpunit so any help would be appreciated.

**Comment by pattonwebz** [comment]
Since last year I have invested some time into learning more about usage of PHP Unit and am now able to write a good subset of tests for various different parts of the walker. I have started adding those to the upcoming version.

Closing this issue for now and can reopen in future once better tests are in place.
