### ISSUE TITLE
Review and Tag all past versions

### ISSUE THREAD

**Issue by bhubbard** [wp-bootstrap/wp-bootstrap-navwalker#262]

**Comment by bhubbard** [comment]
@twittem When you get the chance maybe you can help with this one, the change log has the following versions listed below, but none are tagged in git. I did find one commit for 1.1.0 using git log, but none of the other commits listed the version.

2.0.3
2.0.2
2.0.1
2.0.0

**Comment by SideQuestDIY** [comment]
Yeah I can take a look at this.

Until, 2.0.4 I was manually versioning with no official releases as at the time it was mostly for me to track changes.

**Comment by pattonwebz** [comment]
Closing this one out, I don't think we need to tag old versions going this far back and would be hard to pinpoint specific changesets to version numbers from 4 or 5 years back. especially since I am certain that at some point I probably but in changes without bumping version number :stuck_out_tongue_closed_eyes:
