### ISSUE TITLE
Gulp Script to Deploy Versions/Tags

### ISSUE THREAD

**Issue by bhubbard** [wp-bootstrap/wp-bootstrap-navwalker#266]
It would be useful to have a gulp script to deploy versions and/or tags as needed.

**Comment by pattonwebz** [comment]
Hey @sfgarza,

Is this something that you are still working on? I'm looking to close old or inactive issues and this one hasn't been updated in a while. 

I think that also this may be possible through composer since the repo is now available through packagist.

Closing for the moment but reopen if you continue to work on this.
