### ISSUE TITLE
Composer install location

### ISSUE THREAD

**Issue by j-bull** [wp-bootstrap/wp-bootstrap-navwalker#284]
#### Steps to reproduce the issue:
Run composer require.

#### What I expected:
The class to appear in the vendors folder within my theme.

#### What happened instead:
The class appeared in 'wp-content/plugins/' within my theme dir.

I often use this class as a dependency of a Wordpress theme, not Wordpress, so my `composer install` is done from the theme directory. 

Is there a reason the packagist version drops itself in to the plugins folder (in the wrong place in my instance) rather than the usual vendor folder?

**Comment by pattonwebz** [comment]
I'm not very familiar with composer but this doesn't seem like the intended placement. Do you think the issue is due to this [`type` setting in the walker composer.json](https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/master/composer.json#L4) file?

`"type": "wordpress-plugin",`

Could you share the themes composer file so that I could test the behavior on my end?

**Comment by j-bull** [comment]
Hi @pattonwebz 
If you `composer init` in a theme dir, and then run the `composer require` command, that's probably the easiest way to replicate my issue. For me, it installs the package in '/wp-content/themes/theme/wp-content/plugins/', where 'theme' is the location of my composer.json.

It may be being placed there because of the `"type": "wordpress-plugin"` and the composer-installer dependency. I appreciate the packagist version has also been built as a plugin, but I'm not sure why, as in use, the nav walker is just a single class and can be loaded in via PSR4 as a theme dependency.

**Comment by kyle-mccarthy** [comment]
@pattonwebz This is because of `"type": "wordpress-plugin"`.  Would you be able to change it to `"type": "library"` so it gets installed to the vendor folder?  [The root/sage org](https://roots.io/wordpress-plugins-with-composer/) has a blog post about having the type set to wordpress-plugin.

@j-bull You can get around this by requiring the package normally and adding this to your composer file...

     "extra": {
         "installer-paths": {
         "vendor/wp-bootstrap-navwalker": ["wp-bootstrap/wp-bootstrap-navwalker"]
        }
      }

[Source](https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md)


And you will also want to tell composer to autoload it.

    "autoload": {
       ...
      "files": [
        "vendor/wp-bootstrap-navwalker/class-wp-bootstrap-navwalker.php"
      ]
    }

**Comment by pattonwebz** [comment]
I made a separate issue (noted above) to see if anyone wanted to share an opinion on making this type switch before I pushed it to master. If you guys could leave a comment in there that would be great. 

I agree expected behavior will almost always be to include it inside the theme instead of outside of it. My only concern is the effect it may have on anyone already using this due to the directory switch. I'd rather avoid breaking anyone's setups or causing them unnecessary work if I can avoid it.

**Comment by pattonwebz** [comment]
The package type was changed in master with commit https://github.com/wp-bootstrap/wp-bootstrap-navwalker/commit/88959a70e587b4a19717e864e197e8b7cef6ae0e. 

Going forward the package type is likely to remain `library` as that seems like it's the most useful for people.
