### ISSUE TITLE
Drop-down links are linked but when clicked nothing happens

### ISSUE THREAD

**Issue by codysnodgrass** [wp-bootstrap/wp-bootstrap-navwalker#315]
#### Steps to reproduce the issue:
Go here, http://e27.486.myftpupload.com/hospice/ and click on one of the menu items on the left that have the caret for the drop-down. The drop-down works and the items listed are linked correctly. When you try and click on one of the drop-down items nothing happens.

#### What I expected:
Click on drop-down item it should go to the page.

#### What happened instead:
Nothing happens. I checked the JS console and other Inspect Element tools and don't see any errors related to the drop-down links.

**Comment by pattonwebz** [comment]
Hey @codysnodgrass, I can see the problem you describe however I do not know the exact cause. I feel the same as you - that some JS is catching the click and preventing it somehow - but I do not see any notices in console or any specific code targeting these links in any of the other js files I took quick glances at on the site.

I am thinking one potential cause is due to duplicate `id`s between items in the upper menu and the items in the left menu. The Bootstrap JS probably catches links from the dropdown and back peddles to find what actions need taken. Since the JS finds the first of the duplicate manu `id`s and sees the dropdown is closes it may not be taking actions that it should. NOTE: This is just a best guess and speculation at what is happening, I have not been able to spot an actual problem as of yet :(

**Comment by codysnodgrass** [comment]
Thanks @pattonwebz, I changed the IDs and still experience the issues. I disabled all but necessary plugins and still had the issues.

**Comment by codysnodgrass** [comment]
Just figured it out! I tried just doing a regular menu in the sidebar and removed the walker stuff. I was still having issues with any drop-down links working. I then renamed the surrounding ID which was set to sideMenu. When I changed that the drop-down links worked! Gave it a new ID name and now I don't have issues. I'm not sure why the sideMenu ID would cause the issues.

**Comment by pattonwebz** [comment]
Hmmm that is a peculiar one for sure... I guess something targets `#sideMenu` somewhere?? Regardless I'm glad you got this solved! :)

There was someone the other day asking about support of vertical menus and I was unable to answer them however I see your menus work exactly like they were asking for. Was there a guide you followed that I could link to as reference in the future? Or could you write a mini-guide for us to add to the readme? https://github.com/wp-bootstrap/wp-bootstrap-navwalker/issues/309

**Comment by codysnodgrass** [comment]
Provided a screenshot and my code and CSS on the other topic.
