### ISSUE TITLE
sub menu items that are also links to archives no longer link

### ISSUE THREAD

**Issue by jmdelgadoh** [wp-bootstrap/wp-bootstrap-navwalker#317]
Thanks for this walker function! It works like a charm, but i am having a couple of issues. One of my menu items that has a submenu is also a link to the archives page of those sub-pages, which are custom post types. With the walker function that submenu's href is being assigned just an "#" 

I found where the code is assigning this so i see it's by design, not sure how i could modify it so that it retains the original href, any suggestions would help, thanks!

-xun

**Comment by jmdelgadoh** [comment]
I almost want to say nevermind, I figured out how to get the URL to display now, however eveidently clicking on the menu item only opens the dropdown and there is no way to navigate to the link. It makes sense to me why that's happening, ideally i would be able to just get it to display the dropdown if you click the caret or glyphicon, but not yet sure how to modify that

**Comment by pattonwebz** [comment]
Hey @jmdelgadoh,

Yes this happens by design. We put an `#` as the source because that's the best practice for accessibile links that act as toggle triggers. 

Even if the link is output to the `src` attribute it does not behave the way you expect because there is some JS that powers the dropdowns catching the click event instead of allowing the redirect to happen.

I would encourage you for accessibility to retain the _uppermost link as toggle only_ behaviour. If you need to make the top item link work again you can restore it to the `src` in the walker but it will also need a little JS bound to the click event of the link that redirects to the value in the `src` attribute so that you can reestablish link behaviour after the bootstrap JS catches and prevents it.

**Comment by jmdelgadoh** [comment]
I see! Alright, thanks so much for your comments man! I will follow your advice, thanks!

**Comment by pattonwebz** [comment]
While this issues is not truly _solved_ I feel like it's ok to close it out now as some form of resolution was found. 

If you feel like you definitely do want the links to be kept in the `src` and needed some help writing JS to restore the link behavior to them then reopen this issue and I will be happy to help if I can :)

**Comment by alexey13** [comment]
Good day! Can you please help with that? How to store link in src?
