### ISSUE TITLE
Navwalker doesn't apply classes to anchor elements

### ISSUE THREAD

**Issue by proevilz** [wp-bootstrap/wp-bootstrap-navwalker#319]
Hi,

I have been using this Navwalker for all my BS3 sites and recently wanted to try out BS4 Beta. The BS4 navwalker you provide does not add the `.nav-link` class to the anchor elements within the `li` tags. Everything else appears to work as expected though.

How can I resolve this issue?

**Comment by pattonwebz** [comment]
Hey @legionio,

The `v4` branch does add the `.nav-link` class to the anchors inside the list items. It only omits them if the link in inside a dropdown - in which case they use `dropdown-item` instead.

https://getbootstrap.com/docs/4.0/components/navs/#using-dropdowns
https://github.com/wp-bootstrap/wp-bootstrap-navwalker/blob/v4/class-wp-bootstrap-navwalker.php#L133-L140.

Did the markup change between Bootstrap 4 beta1 and the latest dev version?

**Comment by proevilz** [comment]
Hi @pattonwebz 

I'm using the `v4` branch I do not believe the markup has changed but I'm using `4.0.0`

I am using: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css CDN.

But the classes definitely _aren't_ being added to the anchor tags for me... which is strange. I am using the http://html5blank.com theme so I doubt it could be to do with that as it's pretty much empty. It's also worth noting that the BS3 Navwalker works fine with html5blank theme. The menu has also been registered in my functions.php. 

Here is my navbar code - using the example provided:
```
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

        <?php
        wp_nav_menu( array(
            'theme_location'    => 'primary',
            'depth'             => 2,
            'container'         => 'div',
            'container_class'   => 'collapse navbar-collapse',
            'container_id'      => 'bs-example-navbar-collapse-1',
            'menu_class'        => 'nav navbar-nav',
            'fallback_cb'       => 'WP_Bootstrap_Navwalker::fallback',
            'walker'            => new WP_Bootstrap_Navwalker())
        );
        ?>
		</div>
</nav>
```

And below is a screenshot of the result

![capture](https://user-images.githubusercontent.com/16267903/31397224-5dee699e-addd-11e7-921d-e34891591173.PNG)


Any debug advice would be appreciated.

**Comment by proevilz** [comment]
@pattonwebz Please see my improved reply.

**Comment by pattonwebz** [comment]
@legionio I may be mistaken that this is in the current v4 branch and I'm on mobile just now to so it's quite hard to check what code is where. The code in this PR is ahead of the v4 branch #307 and the changes to get classes in the right places might be in it. I also have a _maybe slightly different_ version of the walker in a theme I built recently that you could look at to see if there are differences. It's on .org repo if you wanted to test install that: https://wordpress.org/themes/best-reloaded/. That is the theme I checked with earlier and it shows the `.nav-link` on the `<a>`, but `.dropdown-item` on the `<a> inside dropdowns.

Once I'm back at my computer I'll look more closely at things and see where I've put the most recent v4 version.

**Comment by proevilz** [comment]
@pattonwebz 

I have tried the #307  commit and the walker from inside the best-reloaded theme and still no success. I have also reverted back to a default WP theme and disabled all plugins and even after that, no classes are inserted into the anchor tags. 

Do you have an ETA on when you'll be able to look into this in more depth/be at your PC?

**Comment by pattonwebz** [comment]
Hey @legionio, sorry I took so long to get back to you. I can look more into this today. 

The first thing I notice is the markup in your screenshot doesn't seem to be coming from our walker class (unless it's a very old version of it). The list items don't show the schema that is output by the walker. We have this on every `li` `itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement"`.

The `.nav-link` outputs for me when using the theme I mentioned in a previous comment and also if I replace the walker in that theme with what is currently in the `v4` branch. I am not sure what is preventing it from triggering on your installation. Do you have anything in the logs that refers to the class file being included or maybe something about a nonexistent object?

The demo I tested this on is here: http://funny-bird.w4.poopy.life/ it's just an empty WP install with the theme added and a basic menu created. 

You can use this link to clone the site and see how it is setup yourself http://poopy.life/create?src=funny-bird&key=frYAFLBacI2jnlok

I added the `.nav-link` outputtung on the `<a>` in this commit for the v4 branch: https://github.com/wp-bootstrap/wp-bootstrap-navwalker/pull/282/commits/9cfa5a4a4f72e82c1a87a5b9840e5cd7c88ace33 so it should be working on your end.

Are you able to share the code for the theme your working on so that I could install the theme locally and look at it more closely?

**Comment by kohmaeda** [comment]
Hi. I had this exact same problem with classes not being added to \<a>. It turns out I had the walker installed as a plugin too (and had forgotten about it). I disabled the plugin and now everything works great.

**Comment by proevilz** [comment]
Hello,

Sorry for the delay in my response.

It appears the issue was with my server. There was an extremely strange caching issue... but thanks for digging into this for me.

Regards

**Comment by pattonwebz** [comment]
Hey @legionio,

I am glad you got this sorted and no problem for digging into things a little, that's what I'm here for :) I just wish I had figured it out haha

Was the original menu stored in a transient or something?

**Comment by proevilz** [comment]
@pattonwebz 

To be honest, I'm actually sure. The issue I had was, I could edit a template file, save it, re-upload it to the server but the changes didn't take effect when I viewed them on the front end e.g. a CSS change or an HTML change. The weird part is that if I deleted the affected file, WP would throw a not found error... so then if I restored it back, there would be no error. This means WP is able to locate/access the file despite still outputting the **old** code. It was really odd... Oh well!

**Comment by pattonwebz** [comment]
Ahh ok I see. It sounds to me like an opcode cache was available to PHP and it was set to not force any checking for file modifications. In dev mode caching is usually so much of a nuisance that I turn off almost completely in local setups (and do the cache testing on a staging server).

PHP is usually compiled into opcodes at runtime and those opcodes are what is executed. An opcode cache stores the compiled file ready to execute - so that next time it doesn't need compiled from the text file into opcodes. 

It sounds like in your case it was set not to `stat` the original file and instead hold the existing version for a very long time (over a few days). That kind of setup works well in production paired with a cache buster but in dev it just gets in my way lol

The opcode cache on your dev server might powered by APC (if it's on PHP < 5.6) or probably Zend Optimize+. You can read a little bit about them and other PHP accelerators here: https://en.wikipedia.org/wiki/List_of_PHP_accelerators
