### ISSUE TITLE
Dropdown caret not showing for parent dropwdown tab

### ISSUE THREAD

**Issue by markmadedesign** [wp-bootstrap/wp-bootstrap-navwalker#337]
Hi! I love the navwalker and have been using it on several sites over time. However, on this particular project the caret is not showing for my dropdown nav tabs and I don't see the span appearing in the source code. Any idea on why this is happening?

Problem site (click on some of the tabs to see which ones where the dropdown works but no caret showing, e.g. ABOUT):
http://devbiolife.com/

Here's an older site where it works just fine using the navwalker:
http://hendersoninc.com/

Any help on the matter would be greatly appreciated! Thanks for creating this and allowing control over Boostrap navigation in Wordpress.

Thanks,
Mark

**Comment by pattonwebz** [comment]
Hey @markmadedesign,

The link to the site where it isn't working is just showing a 'Coming soon' page for me.

Just to confirm are you using Bootstrap 3 on the devbiolife site?

**Comment by pattonwebz** [comment]
Hey @markmadedesign,

I am trying to clear out issues to make way for a large rewrite to the walker for bootstrap 4 and the future influx of potential issues from that. Since the link to preview the site is currently not showing the menu and I haven't heard back from you yet I'm closing this issue but please reopen it if you are still having this problem and need help finding a solution.

**Comment by smrtrnx** [comment]
Hello,

The latest version 4 of navwalker isn't showing the caret's on the top level menu also with the second level menu which has children menus in it.

Any solutions for this issue?
