### ISSUE TITLE
when dropdown is open click on it open it's page

### ISSUE THREAD

**Issue by hameds1** [wp-bootstrap/wp-bootstrap-navwalker#351]
when click on a dropdown menu, it open and when click on it again or everywhere else it close
i want when click on dropdown, it open but when it is open click on it open its page not close dropdown.
because i have a services page and several sub-services and i want my customer can see main services page and sub-services pages

**Comment by pattonwebz** [comment]
Hey @hameds1,

I am not completely clear on what you are trying to achieve but it sounds like you are trying to make the top level item (the item you click to open the dropdown) into a linked item - but only linked when dropdown is open.

Top level linked items is not something that the core Bootstrap scripts support (and it does not have logic for opening the dropdown and then swapping the link behaviors). This navwalker only provides access to the features offered by Bootstrap - it does not add any new features of it's own.

There are other issue threads in this repo where it has been discussed about how to make top level items linkable - you should be able to find that information with the search feature. 

As for making it both a link opener and a link itself: I am unsure how you would achieve that. Perhaps a better option would be for you to investigate making the carat that appears beside dropdowns into a clickable element for open/close dropdowns.

Since this one is beyond the scope of this project I'm going to tag the thread and close it but feel free to continue the conversation here even once the thread is closed - just ping me if you need me :)

**Comment by hameds1** [comment]
tnx
i use from hover and click together.
i change this codes in navwalker: 
```
if ( $args->has_children && 0 === $depth ) {
    $atts['href']          = ! empty( $item->url ) ? $item->url : '';
    //$atts['href']          = '#';
    //$atts['data-toggle']   = 'dropdown';
}
```
and use js to add hover in desktop mode and remove in mobile mode:

```
(function($) {
    function mediaSize() {
        if (window.matchMedia('(max-width: 767px)').matches) {
        $('.dropdown a').attr('data-toggle','dropdown');
        } else {
            $('.dropdown a').removeAttr('data-toggle');
            $('li.dropdown').mouseover(function(){
                $(this).addClass('open');
            });
            $('li.dropdown').mouseleave(function(){
                $(this).removeClass('open');
            });
        }
    };
  mediaSize();
    window.addEventListener('resize', mediaSize, false);  
})(jQuery);
```

Edit reason: adding backticks for better display of code blocks.

**Comment by pattonwebz** [comment]
Hey @hameds1,

That seems like a nice and easy solution to solve your problem. 

I am sorry I could not be of more help in finding the solution but I am very happy that you managed to solve it in such a nice way. 

And thank you for returning to post the solution incase others needed it in future :)
