### ISSUE TITLE
Dropdown Nav Issues on Mobile

### ISSUE THREAD

**Issue by Mebula** [wp-bootstrap/wp-bootstrap-navwalker#363]
I'm creating a custom theme on Wordpress and am having issues getting the nav dropdown to work on mobile. When I try clicking on the dropdown menu, it drops down for a second, and then disappears again. This is my first time creating a Wordpress theme, so apologies if this is a really simple question

Here's what I have in header.php:
<img width="565" alt="screen shot 2018-04-06 at 1 27 57 pm" src="https://user-images.githubusercontent.com/28746290/38435069-8fd27ac0-399e-11e8-822b-314c2d49fa60.png">

(I commented out the container div because it was messing up my layout, but when I used it nothing changed.)

This is what I have in functions.php:
<img width="588" alt="screen shot 2018-04-06 at 1 33 14 pm" src="https://user-images.githubusercontent.com/28746290/38435295-3bebb812-399f-11e8-8eba-ba9e9fff772b.png">
<img width="554" alt="screen shot 2018-04-06 at 1 33 49 pm" src="https://user-images.githubusercontent.com/28746290/38435299-409ea2e8-399f-11e8-8639-7b4f41e97880.png">

Here's what my menu looks like on mobile:
<img width="361" alt="screen shot 2018-04-06 at 1 22 26 pm" src="https://user-images.githubusercontent.com/28746290/38434789-a4c571c2-399d-11e8-914b-7328b35aeea4.png">

For reference, this is what I have on the HTML version of the site, and it works fine.
<img width="623" alt="screen shot 2018-04-06 at 1 28 53 pm" src="https://user-images.githubusercontent.com/28746290/38435345-5f13ceba-399f-11e8-9ede-fb67f0ceb2a1.png">

If anyone could provide some help or guidance it would be much appreciated! I've been pulling my hair out over this issue.

Thanks!

**Comment by pattonwebz** [comment]
Hey @mebula,

Pasted code would be better than screenshots in most cases. I'm not able to test out your code on my end because I'm not able to paste it into my test instance.

From glancing at the code only 1 thing stands out to me - your using BS 4 CSS file from CDN but the the JS is local and says 3.0.0 in the version string. Are you using Bootstrap 4 or Bootstrap 3?

Other than that a quick Google shows that there _may_ (I did not read them closely) be conflicts with Bootstrap and Slick when jQuery is in `noConflict` mode. Wordpress puts jQuery into no conflict mode by default.

**Comment by pattonwebz** [comment]
Hey again @Mebula,

Done a little more testing on my end I am still unable to recreate this problem. Again I did not test your exact code (I'm not typing out from screenshots - I *will* make mistakes if I do that lol).

Could you paste in your code for me and I'll try things with your exact code? Also do any console errors get thrown from anything on your end that could indicate an area to investigate?

Also if you are able could you try it without `slick` added. If problem persists even without slick that rules that out as being the culprit for conflict.

I'm around to help if I can, just ping me :)

P.S. I do not think this is a problem with the walker. I'm tagging as implementation issue - that does not mean I am saying you have made an implementation error (code looks ok to me from the screenshots), it just means that I think this problem is caused by one. Probably an external conflict I cannot see from these screenshots.

**Comment by Mebula** [comment]
hi @pattonwebz thanks for the quick response! So it the issue was with the using the BS 3 JS rather than the BS 4 version... totally my mistake for not having had updated it yet. Once I got that fixed it started working perfectly! Doesn't look like Slick was causing an issue on anything.

Sorry about the screenshots thing! Like I said, kind of a noob here >.< but noted for the future!

Again, really appreciate the speedy response! Hope I didn't waste too much of your time

EDIT ADDED BY @pattonwebz:
On github you can add code blocks by wrapping text in backticks. Inline code can be wrapped with a single backtick on either end like so: `code`.

```php
// multiline comments are surrounded by 3 backticks on the line 
// above and 3 on the line below.
```

**Comment by pattonwebz** [comment]
Hey @Mebula,

Glad you got it sorted and you do not worry because you did not waste my time at all. While looking into possible causes I found out a couple of other things that were worth knowing anyways. Your issue is fixed and I learned some new things. Win-Win :smile:.

The screenshots are ok (in this case it helped out spot the issue anyway) but is better to provide code where you can that people can copy. Don't trust people to type out your code and make no mistakes (I know I would make mistakes retyping which is why I didn't lol).

On github you can add code blocks by wrapping text in backticks. Inline code can be wrapped with a single backtick on either end like so: `code`.

```php
// multiline comments are surrounded by 3 backticks on the line 
// above and 3 on the line below.
```

Anyways good luck with this project and I'm happy you got a solution. And welcome to code collaboration and issue reporting on github. We were all noobs here once so no need to apologize.

**Comment by pattonwebz** [comment]
@Mebula  I just edited your previous comment and added my examples of adding codeblocks in github to it. You should be able to click edit on your comment and see how they were added to the text. Seeing an example is probably easier to understand than my text description :)

**Comment by Mebula** [comment]
@pattonwebz Thanks so much for your help! And I will be sure not to use screenshots from not on haha.  It definitely leaves room for error.

(PS sorry for my late response, been offline the last few days!)
