### ISSUE TITLE
Dropdown menu 

### ISSUE THREAD

**Issue by thaobn20** [wp-bootstrap/wp-bootstrap-navwalker#373]
Dear Author

I have using you code but this not show drop down menu

**Comment by pattonwebz** [comment]
Hey @thaobn20,

Sorry you are having issues. I am not sure what to suggest without getting a little more information from you. Could you post the code you use for the `wp_nav_menu()` call?

The only thing I can think of is that maybe you did not set `'depth' => 2,`?

If that doesn't work if you can share some of the code you used to make the manu I may be able to spot something that could be causing it. I'm around to help if I can :)

**Comment by pattonwebz** [comment]
Is the `depth` paramiter you have used `'depth' => 1`? I have just spotted a place in the readme where it incorrectly had an inline comment that said ` `// 1 = with dropdowns, 0 = no dropdowns`. That is incorrect and I will push a fix for it shortly.

The correct comment should be this `'depth' => 2, // 1 = no dropdowns, 2 = with dropdowns.`.

Is that what the problem was?

**Comment by pattonwebz** [comment]
If the issue here was caused by the mistake in the readme then it will be fixed when I merge this in #374 :)

**Comment by pattonwebz** [comment]
I'm going to assume that you either managed to fix this or work around it on your own and that it was due to the issue in the readme stating incorrect depth values.

If the issues is not related to the `depth` parameter then comment and I will reopen the ticket and try to help however I can.
