### ISSUE TITLE
Enable menu edit shortcut

### ISSUE THREAD

**Issue by nithinkvarrier** [wp-bootstrap/wp-bootstrap-navwalker#407]
#### Steps to reproduce the issue:
When I enabled wp-bootstrap-navwalker class, the editshortcut icon not displaying.

**Comment by pattonwebz** [comment]
There are some problems with how the walker is importing into customizer which I have not been able to solve yet. I am looking into them though and trying to work it out. Thanks for highlighting this for me!

**Comment by rafasashi** [comment]
Any update on this one?

**Comment by IanDelMar** [comment]
According to
- https://make.wordpress.org/core/2015/07/29/fast-previewing-changes-to-menus-in-the-customizer/
- https://wordpress.stackexchange.com/questions/281854/
- https://wordpress.stackexchange.com/questions/295461/

the problem seems to be that the walker instance is not JSON serializable. To solve this you have to
1. provide a string instead of an object as value for the 'walker' key in the array of wp_nav_menu's arguments, and
2. provide the walker object via a filter.

Concerning the first point, do the following when calling `wp_nav_menu()`
```diff
wp_nav_menu( array(
    'theme_location'  => 'primary',
    'depth'           => 2, // 1 = no dropdowns, 2 = with dropdowns.
    'container'       => 'div',
    'container_class' => 'collapse navbar-collapse',
    'container_id'    => 'bs-example-navbar-collapse-1',
    'menu_class'      => 'navbar-nav mr-auto',
    'fallback_cb'     => 'WP_Bootstrap_Navwalker::fallback',
-    'walker'          => new WP_Bootstrap_Navwalker(),
+    'walker'          => 'WP_Bootstrap_Navwalker',
) );
```
Concerning the second point, add this to your functions.php
```php
function slug_provide_walker_object( $args ) {
    if ( isset( $args['walker'] ) && is_string( $args['walker'] ) && class_exists( $args['walker'] ) ) {
        $args['walker'] = new $args['walker'];
    }
    return $args;
}
add_filter( 'wp_nav_menu_args', 'slug_provide_walker_object', 1001 );
```

There is an [open ticket](https://core.trac.wordpress.org/ticket/14142) addressing the fatal error which is thrown if you provide a string without adding the filter in 2..

@pattonwebz how to handle this in v5? Shall we update the readme to use a string and provide the filter? Shall we restrict the filter to this walker then or should it be applied to all walkers? Or shall we leave it as it is and provide the fix in the readme in case someone needs/wants the edit shortcut?

**Comment by pattonwebz** [comment]
@IanDelMar it seems strange that you need to use a string class name and also add a filter to handle this. With an expectation that the customizer is going away in the not so distant future, I think for V5 we could continue to pass a class instance still but document the filter method in the readme.

Open to your thoughts on the idea though and willing to go with whatever you feel is best.

**Comment by IanDelMar** [comment]
@pattonwebz I tend to agree. Having to use a filter to re-add the instance of the walker we replaced with the class name string looks kind of hacky. I'm not up to date on current WP developments and hence have no idea if and when the customizer will be removed. However, I think using the class name string will probably rise more questions because the [docs](https://developer.wordpress.org/reference/functions/wp_nav_menu/) say you have to provide a class instance. So, let's stick to the instance. I'll make an PR updating the readme accordingly.
