### ISSUE TITLE
Inserting Functions.php code loads the Navwalker Github page on Site

### ISSUE THREAD

**Issue by markmadedesign** [wp-bootstrap/wp-bootstrap-navwalker#439]
Hi. When I add the "Register Custom Navigation Walker" code to my functions.php file and upload to my site, my client's site oddly shows the Navwalker Github page below the site's fixed menu. I've used this on several sites in the past but have never experienced this. Anyone have an idea why this happens? Screenshot attached.

**Comment by pattonwebz** [comment]
Hey, sorry that this has happened to you here. This has been reported before in the past but I have never been able to figure out what causes it or why. I've never been able to recreate it on my end :(

Do you have any more details you could share about the server setup, it's configuration etc that might help me figure out what the root cause of it is?

**Comment by markmadedesign** [comment]
Thanks for the quick response. Any specific questions about the sever setup / config you have in mind? I need to ask another person handles IT, hosting and web maintenance for this info and just want to make sure I get it right when I reach out.

So strange since I've used this framework in the past with no issues, so I'm intrigued if it's a server conflict. Btw, the site in question is [https://bayaging.org/](https://bayaging.org/).

**Comment by pattonwebz** [comment]
To be honest I am not certain at all about the exact questions to ask regarding your server setup/configs. I have tried a number of things on my end and never managed to recreated this for myself to even see it happen or debug it.

Maybe you could email me the theme (should be able to get my email address from my github profile) which fails and I could test that out locally and see if the same thing happens to me?

**Comment by markmadedesign** [comment]
It is a custom WP theme built on my end using Bootstrap (same sites I've used navwalker with in past have been custom themes) but the core files were duplicated from the "twentynineteen" WP theme and then completely overhauled using Bootstrap. 

Does that help? Would sending you my "functions.php" file help at all? Any other files from my theme? As far as the server goes I do know it's more dedicated and not a shared server.

I would really love to make this work vs going a different route w/ code or even worse, a plugin for the menu,

**Comment by pattonwebz** [comment]
Yeah if you could send through your functions.php file I will try that in a theme in my local and see if that works the same as it does for you.

This one has annoyed me for a long time. The navwalker itself doesn't include any code which loads external urls in any way which is why this is so strange...

**Comment by markmadedesign** [comment]
See attached. Do you get this when I reply via email?

**Comment by pattonwebz** [comment]
@markmadedesign no attachments don't come through that way it seems. You can email me it at `redacted`.

**Comment by pattonwebz** [comment]
We managed to get this one resolved. Github makes it very easy to save the page where the file exists rather than the actual file.
