### ISSUE TITLE
collapse wont work properly

### ISSUE THREAD

**Issue by irmo** [wp-bootstrap/wp-bootstrap-navwalker#49]
I noticed that after i expand the collapsable menu (in the small and extra small screen) it wont collapse again if i click on the button

is that a known issue or i'm doing something wrong?

P.

**Comment by SideQuestDIY** [comment]
If the menu opens and does not close the only issue I can think of is that you are loading additional javascript that contains errors/conflicts. When using the standard Bootstrap 3 JS everything works flawlessly. I have seen this before when additional dropdown on hover scripts are added.

Since the walker only provides the markup necessary for rendering the menu LI's for use with Bootstrap 3, if the HTML is structured correctly the error is not with the walker. 

It's hard to say without seeing the site & code,
