### ISSUE TITLE
Scroll mobile menu

### ISSUE THREAD

**Issue by Kamduras-dev** [wp-bootstrap/wp-bootstrap-navwalker#507]
Hello,

When I create a long menu. On mobiles, you can't scroll and you can't see the bottom of the menu.

Thanks.

**Comment by IanDelMar** [comment]
Hi @Kamduras-dev , would you please provide a screenshot? Thank You!

**Comment by Kamduras-dev** [comment]
> 
> 
> Hi @Kamduras-dev , would you please provide a screenshot? Thank You!

Sure:

![MobileMenu](https://user-images.githubusercontent.com/64219825/106109564-fa9c8280-6149-11eb-8394-7642274e0ab5.png)

**Comment by IanDelMar** [comment]
I'll check that and come back to you.

**Comment by IanDelMar** [comment]
This happens because you use a fixed navbar. If the fixed navbar spans the whole screen (when expanded) you won't be able to visibly scroll. The content behind the fixed navbar scrolls but is hidden by the navbar. The fixed navbar is not scrollable per definition. You can fix this by unsetting the "navbar-fixed" for small/medium screens. Go to https://getbootstrap.com/docs/4.6/examples/starter-template/ using a mobile, expand the menu and scroll to see what's going on. 

This is normal behaviour and not a WP Bootstrap Navwalker bug.

**Comment by Kamduras-dev** [comment]
> 
> 
> This happens because you use a fixed navbar. If the fixed navbar spans the whole screen (when expanded) you won't be able to visibly scroll. The content behind the fixed navbar scrolls but is hidden by the navbar. The fixed navbar is not scrollable per definition. You can fix this by unsetting the "navbar-fixed" for small/medium screens. Go to https://getbootstrap.com/docs/4.6/examples/starter-template/ using a mobile, expand the menu and scroll to see what's going on.
> 
> This is normal behaviour and not a WP Bootstrap Navwalker bug.

Thank you very much, I hadn't thought of that.

Thank you for your time.

I close the issue

**Comment by IanDelMar** [comment]
You're welcome!
