### ISSUE TITLE
Ability to have dropdown be split button eg link / caret

### ISSUE THREAD

**Issue by erikflowers** [wp-bootstrap/wp-bootstrap-navwalker#51]
On sites like Font Awesome, their main nav functions like this:
1. The parent links are all clickable to a primary page, eg "icons" just goes to the icons page
2. The dropdowns are activated by clicking the caret. 

Example of the split button: http://getbootstrap.com/components/#btn-dropdowns-split

This would be a great addition, I am guessing though it would have to be specified somehow as there's no way to know if it should build the standard dropdown, or a split button.

I am no PHP programmer, so while I can help with bootstrap html/css, making it actually **work** is out of my reach /cry. I am happy to take part in trying ot make this a feature though and plan to experiment with it a bit and see if I can at least run in to some useful errors. 

Please respond here if you have more questions on my use case. 

![screen shot 2013-11-26 at 10 44 17 am](https://f.cloud.github.com/assets/913115/1624472/9301c75a-56c2-11e3-85ff-bcede4a82ac6.png)

**Comment by SideQuestDIY** [comment]
Hey @erikflowers, 

Thanks for the feedback.

Unfortunately this is not something that would be added to the class.

**The reasons for this are two fold:**
1. The class is intended to implement standard Bootstrap 3 menus with no additional features, JS or CSS. 
2. This brakes Bootstraps mobile first mindset. Setting up the menu this way would cause broken and unexpected issues on tablets and some mobile devices. Adding the additional split to each menu item would create a lot of additional markup that would need to be hidden or altered with javascript in a responsive scenario. When a table is in landscape responsive sites typically display the desktop version, and will our meaty fingers requiring a recommended 60px by 60px hitspace there would be unintentional clicks.

Looking at it from a UX standpoint I often challenge other to rethink their menu structure. A menus should ultimately be the simplest form of navigation possible. 

**Here are my personal navigation rules:**
1. _If your menu item has a dropdown, there is no need for a parent page._ This content is often redundant and just another roadblock on the way to relevant content. Do I need to click a services button to see your offer services? or should go directly to the relevant content? Yes, sometimes parent pages are useful for SEO landing but this does not mean they need to be included the main navigation.
2. _If your dropdown links to content inside a parent page (not its own page) it has no place in the main navigation and should be moved to page specific navigation._ Navigation the produces unexpected results is always bad for user experience. 
3. _Never dropdown on hover. Navigate with intention._ There is nothing more annoying than trying to use a drop down menu and having it disappear because your mouse is in the wrong position, or accidentally clicking the parent. This also solves many issues on mobile. Clicking to dropdown allows mobile users to access the submenu items instead of being directed to a parent page. Mobile users move quickly and with intention, if they are forced to load additional pages of struggle to navigate they will bounce.
4. _Always Remember to KISS._ Keep it simple, stupid. Problems with websites are not the fault of web browsers or users. Problems with websites arise when we needlessly over complicate things. The less HTML, CSS & Javascript we can load, the less potential we create for user confusion, the better the web will be. 

## 

Haha, sorry to rant.

**Comment by erikflowers** [comment]
This was a good read. I get the technical and ux arguments. I like this sort of thought process and inclined to agree with you
