### ISSUE TITLE
Multilevel Dropdown

### ISSUE THREAD

**Issue by jerrylopez** [wp-bootstrap/wp-bootstrap-navwalker#60]
Hello. There's something that has been boggling my mind a bit and that is multilevel dropdowns. I've never really needed it before but now that i am building an online store for a retail company and I need 3-4 levels. I've looked around but have only found CSS alternatives that don't work in mobile. I know this may be a more bootstrappy question but I figured that it would be something nice to add to your nav walker. What are your thoughts on this?

**Comment by SideQuestDIY** [comment]
This walker purposely does not support multi level drop downs and it is only intended to implement Bootstrap 3. Multi Level drop-downs were removed from Bootstrap 3 as they are difficult to support on mobile, and often completely unnecessary. Personally, I feel the issue lies more with content structure then the need for deep drop-downs,

I have built quite a few e-commerce site and I actually find the more simplistic your menu structure is the greater conversion happens. When I do things now I only have the top level items in the menu and use in page navigation specific to the section/category.

![wireframe](https://f.cloud.github.com/assets/1471150/1824841/e973dcf0-71a1-11e3-877d-458dadfc8a42.png)

This means that on category landing pages you have great real estate to showcase featured products and its still simple for the user, it also means that you can continue the navigation scheme throughout the site. 

With that said Bootstrap 2.3.2 did support multiple levels and if you would like to use multilevel dropdowns I would suggest using my Bootstrap 2.3.2 walker ( https://github.com/twittem/wp-bootstrap-navwalker/tree/For-Bootstrap-2.3.2 ) or taking a look at this pull request https://github.com/twittem/wp-bootstrap-navwalker/pull/52
