### ISSUE TITLE
Parent text does not trigger dropdown in mobile view.

### ISSUE THREAD

**Issue by EminenceHC** [wp-bootstrap/wp-bootstrap-navwalker#78]
When in mobile view, I can uncollapse a parent item to see its children only by clicking the tiny arrow to the right. I would like to be able to click the actual title to see the children. Is this not currently supported or is it a bug? Is there anyway I can implement this functionality?

**Comment by SideQuestDIY** [comment]
That is quite odd as the anchor wraps the entire menu item.
-  Is there a sample URL I can take a look at? 
- What mobile browser & OS are you using?

**Comment by EminenceHC** [comment]
wordpress.eminencehc.com

I am using a mobile chrome version on my android 2.2 phone, although, I have tried it in Safari and Chrome on a desktop and the same problem occurs when in mobile view.

Thanks!

**Comment by EminenceHC** [comment]
P.S. I made you an admin account, let me know if you don't get the email or password.

**Comment by SideQuestDIY** [comment]
Interesting, your menus seem to be a highly modified to extend what bootstrap supports. (like dropdown on hover & top level page links) and by the looks of it the wp-bootstrap-navwalker class has been modified as well. I can tell because the shortcodes link takes you to a top level page (these are disabled in the walker to ensure mobile support) and if you look at the code the standard Bootstrap dropdown triggers are not output.

Because of these modifications there is not really anything I can do to assist as it seems to be a javascript conflict with functionality that is not supported by the Bootstrap library.

**Comment by EminenceHC** [comment]
Hmm, alright I will check with the themer. I really appreciate you taking the time to look around. You are a very good maintainer. Thanks!

**Comment by SideQuestDIY** [comment]
No problem, wish I could do more but a large portion of the functionality has been modified so its almost impossible for my to troubleshoot without going line by thing through the PHP & JS files.
