### ISSUE TITLE
Menu item with child/sub menus is not clickable

### ISSUE THREAD

**Issue by farukgaric** [wp-bootstrap/wp-bootstrap-navwalker#8]
Hi, thank you for excellent solution. My question is why menu item isn't clickable if he has submenu items? How solve that?

Tnx in advance!

**Comment by SideQuestDIY** [comment]
The parent menu item is not clickable as a link because that is how things are done with the bootstrap framework. 

The reason for this is that drop down menus do not pop open on hover as most people are used to, but on click. This is so that the menus system is usable on mobile devices such as tablets and cell phones. If you change this you will not be able to access sub-menu items on a mobile device.
